/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebParaSectorRouteImport } from './routes/web-para-$sector'
import { Route as WebConReservasRouteImport } from './routes/web-con-reservas'
import { Route as SeoLocalRouteImport } from './routes/seo-local'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as MantenimientoWebRouteImport } from './routes/mantenimiento-web'
import { Route as LandingPageRouteImport } from './routes/landing-page'
import { Route as GoogleBusinessProfileRouteImport } from './routes/google-business-profile'
import { Route as DisenoWebSeoRouteImport } from './routes/diseno-web-seo'
import { Route as DisenoWebParaEmpresasRouteImport } from './routes/diseno-web-para-empresas'
import { Route as DisenoTiendaOnlineRouteImport } from './routes/diseno-tienda-online'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeoLocalCiudadRouteImport } from './routes/seo-local.$ciudad'
import { Route as PortfolioProyectoRouteImport } from './routes/portfolio.$proyecto'
import { Route as DisenoWebCiudadRouteImport } from './routes/diseno-web.$ciudad'
import { Route as BlogCuantoCuestaPaginaWebRestauranteRouteImport } from './routes/blog.cuanto-cuesta-pagina-web-restaurante'
import { Route as BlogCuantoCuestaPaginaWebEspanaRouteImport } from './routes/blog.cuanto-cuesta-pagina-web-espana'
import { Route as LandingTypeCiudadRouteImport } from './routes/$landingType.$ciudad'

const WebParaSectorRoute = WebParaSectorRouteImport.update({
  id: '/web-para-$sector',
  path: '/web-para-$sector',
  getParentRoute: () => rootRouteImport,
} as any)
const WebConReservasRoute = WebConReservasRouteImport.update({
  id: '/web-con-reservas',
  path: '/web-con-reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoLocalRoute = SeoLocalRouteImport.update({
  id: '/seo-local',
  path: '/seo-local',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const MantenimientoWebRoute = MantenimientoWebRouteImport.update({
  id: '/mantenimiento-web',
  path: '/mantenimiento-web',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageRoute = LandingPageRouteImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleBusinessProfileRoute = GoogleBusinessProfileRouteImport.update({
  id: '/google-business-profile',
  path: '/google-business-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenoWebSeoRoute = DisenoWebSeoRouteImport.update({
  id: '/diseno-web-seo',
  path: '/diseno-web-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenoWebParaEmpresasRoute = DisenoWebParaEmpresasRouteImport.update({
  id: '/diseno-web-para-empresas',
  path: '/diseno-web-para-empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DisenoTiendaOnlineRoute = DisenoTiendaOnlineRouteImport.update({
  id: '/diseno-tienda-online',
  path: '/diseno-tienda-online',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoLocalCiudadRoute = SeoLocalCiudadRouteImport.update({
  id: '/$ciudad',
  path: '/$ciudad',
  getParentRoute: () => SeoLocalRoute,
} as any)
const PortfolioProyectoRoute = PortfolioProyectoRouteImport.update({
  id: '/$proyecto',
  path: '/$proyecto',
  getParentRoute: () => PortfolioRoute,
} as any)
const DisenoWebCiudadRoute = DisenoWebCiudadRouteImport.update({
  id: '/diseno-web/$ciudad',
  path: '/diseno-web/$ciudad',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCuantoCuestaPaginaWebRestauranteRoute =
  BlogCuantoCuestaPaginaWebRestauranteRouteImport.update({
    id: '/cuanto-cuesta-pagina-web-restaurante',
    path: '/cuanto-cuesta-pagina-web-restaurante',
    getParentRoute: () => BlogRoute,
  } as any)
const BlogCuantoCuestaPaginaWebEspanaRoute =
  BlogCuantoCuestaPaginaWebEspanaRouteImport.update({
    id: '/cuanto-cuesta-pagina-web-espana',
    path: '/cuanto-cuesta-pagina-web-espana',
    getParentRoute: () => BlogRoute,
  } as any)
const LandingTypeCiudadRoute = LandingTypeCiudadRouteImport.update({
  id: '/$landingType/$ciudad',
  path: '/$landingType/$ciudad',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRouteWithChildren
  '/diseno-tienda-online': typeof DisenoTiendaOnlineRoute
  '/diseno-web-para-empresas': typeof DisenoWebParaEmpresasRoute
  '/diseno-web-seo': typeof DisenoWebSeoRoute
  '/google-business-profile': typeof GoogleBusinessProfileRoute
  '/landing-page': typeof LandingPageRoute
  '/mantenimiento-web': typeof MantenimientoWebRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/seo-local': typeof SeoLocalRouteWithChildren
  '/web-con-reservas': typeof WebConReservasRoute
  '/web-para-$sector': typeof WebParaSectorRoute
  '/$landingType/$ciudad': typeof LandingTypeCiudadRoute
  '/blog/cuanto-cuesta-pagina-web-espana': typeof BlogCuantoCuestaPaginaWebEspanaRoute
  '/blog/cuanto-cuesta-pagina-web-restaurante': typeof BlogCuantoCuestaPaginaWebRestauranteRoute
  '/diseno-web/$ciudad': typeof DisenoWebCiudadRoute
  '/portfolio/$proyecto': typeof PortfolioProyectoRoute
  '/seo-local/$ciudad': typeof SeoLocalCiudadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRouteWithChildren
  '/diseno-tienda-online': typeof DisenoTiendaOnlineRoute
  '/diseno-web-para-empresas': typeof DisenoWebParaEmpresasRoute
  '/diseno-web-seo': typeof DisenoWebSeoRoute
  '/google-business-profile': typeof GoogleBusinessProfileRoute
  '/landing-page': typeof LandingPageRoute
  '/mantenimiento-web': typeof MantenimientoWebRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/seo-local': typeof SeoLocalRouteWithChildren
  '/web-con-reservas': typeof WebConReservasRoute
  '/web-para-$sector': typeof WebParaSectorRoute
  '/$landingType/$ciudad': typeof LandingTypeCiudadRoute
  '/blog/cuanto-cuesta-pagina-web-espana': typeof BlogCuantoCuestaPaginaWebEspanaRoute
  '/blog/cuanto-cuesta-pagina-web-restaurante': typeof BlogCuantoCuestaPaginaWebRestauranteRoute
  '/diseno-web/$ciudad': typeof DisenoWebCiudadRoute
  '/portfolio/$proyecto': typeof PortfolioProyectoRoute
  '/seo-local/$ciudad': typeof SeoLocalCiudadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRouteWithChildren
  '/diseno-tienda-online': typeof DisenoTiendaOnlineRoute
  '/diseno-web-para-empresas': typeof DisenoWebParaEmpresasRoute
  '/diseno-web-seo': typeof DisenoWebSeoRoute
  '/google-business-profile': typeof GoogleBusinessProfileRoute
  '/landing-page': typeof LandingPageRoute
  '/mantenimiento-web': typeof MantenimientoWebRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/seo-local': typeof SeoLocalRouteWithChildren
  '/web-con-reservas': typeof WebConReservasRoute
  '/web-para-$sector': typeof WebParaSectorRoute
  '/$landingType/$ciudad': typeof LandingTypeCiudadRoute
  '/blog/cuanto-cuesta-pagina-web-espana': typeof BlogCuantoCuestaPaginaWebEspanaRoute
  '/blog/cuanto-cuesta-pagina-web-restaurante': typeof BlogCuantoCuestaPaginaWebRestauranteRoute
  '/diseno-web/$ciudad': typeof DisenoWebCiudadRoute
  '/portfolio/$proyecto': typeof PortfolioProyectoRoute
  '/seo-local/$ciudad': typeof SeoLocalCiudadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/blog'
    | '/diseno-tienda-online'
    | '/diseno-web-para-empresas'
    | '/diseno-web-seo'
    | '/google-business-profile'
    | '/landing-page'
    | '/mantenimiento-web'
    | '/politica-de-cookies'
    | '/politica-de-privacidad'
    | '/portfolio'
    | '/seo-local'
    | '/web-con-reservas'
    | '/web-para-$sector'
    | '/$landingType/$ciudad'
    | '/blog/cuanto-cuesta-pagina-web-espana'
    | '/blog/cuanto-cuesta-pagina-web-restaurante'
    | '/diseno-web/$ciudad'
    | '/portfolio/$proyecto'
    | '/seo-local/$ciudad'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/blog'
    | '/diseno-tienda-online'
    | '/diseno-web-para-empresas'
    | '/diseno-web-seo'
    | '/google-business-profile'
    | '/landing-page'
    | '/mantenimiento-web'
    | '/politica-de-cookies'
    | '/politica-de-privacidad'
    | '/portfolio'
    | '/seo-local'
    | '/web-con-reservas'
    | '/web-para-$sector'
    | '/$landingType/$ciudad'
    | '/blog/cuanto-cuesta-pagina-web-espana'
    | '/blog/cuanto-cuesta-pagina-web-restaurante'
    | '/diseno-web/$ciudad'
    | '/portfolio/$proyecto'
    | '/seo-local/$ciudad'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/blog'
    | '/diseno-tienda-online'
    | '/diseno-web-para-empresas'
    | '/diseno-web-seo'
    | '/google-business-profile'
    | '/landing-page'
    | '/mantenimiento-web'
    | '/politica-de-cookies'
    | '/politica-de-privacidad'
    | '/portfolio'
    | '/seo-local'
    | '/web-con-reservas'
    | '/web-para-$sector'
    | '/$landingType/$ciudad'
    | '/blog/cuanto-cuesta-pagina-web-espana'
    | '/blog/cuanto-cuesta-pagina-web-restaurante'
    | '/diseno-web/$ciudad'
    | '/portfolio/$proyecto'
    | '/seo-local/$ciudad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  BlogRoute: typeof BlogRouteWithChildren
  DisenoTiendaOnlineRoute: typeof DisenoTiendaOnlineRoute
  DisenoWebParaEmpresasRoute: typeof DisenoWebParaEmpresasRoute
  DisenoWebSeoRoute: typeof DisenoWebSeoRoute
  GoogleBusinessProfileRoute: typeof GoogleBusinessProfileRoute
  LandingPageRoute: typeof LandingPageRoute
  MantenimientoWebRoute: typeof MantenimientoWebRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  SeoLocalRoute: typeof SeoLocalRouteWithChildren
  WebConReservasRoute: typeof WebConReservasRoute
  WebParaSectorRoute: typeof WebParaSectorRoute
  LandingTypeCiudadRoute: typeof LandingTypeCiudadRoute
  DisenoWebCiudadRoute: typeof DisenoWebCiudadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-para-$sector': {
      id: '/web-para-$sector'
      path: '/web-para-$sector'
      fullPath: '/web-para-$sector'
      preLoaderRoute: typeof WebParaSectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-con-reservas': {
      id: '/web-con-reservas'
      path: '/web-con-reservas'
      fullPath: '/web-con-reservas'
      preLoaderRoute: typeof WebConReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-local': {
      id: '/seo-local'
      path: '/seo-local'
      fullPath: '/seo-local'
      preLoaderRoute: typeof SeoLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mantenimiento-web': {
      id: '/mantenimiento-web'
      path: '/mantenimiento-web'
      fullPath: '/mantenimiento-web'
      preLoaderRoute: typeof MantenimientoWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-page': {
      id: '/landing-page'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-business-profile': {
      id: '/google-business-profile'
      path: '/google-business-profile'
      fullPath: '/google-business-profile'
      preLoaderRoute: typeof GoogleBusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-web-seo': {
      id: '/diseno-web-seo'
      path: '/diseno-web-seo'
      fullPath: '/diseno-web-seo'
      preLoaderRoute: typeof DisenoWebSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-web-para-empresas': {
      id: '/diseno-web-para-empresas'
      path: '/diseno-web-para-empresas'
      fullPath: '/diseno-web-para-empresas'
      preLoaderRoute: typeof DisenoWebParaEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseno-tienda-online': {
      id: '/diseno-tienda-online'
      path: '/diseno-tienda-online'
      fullPath: '/diseno-tienda-online'
      preLoaderRoute: typeof DisenoTiendaOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-local/$ciudad': {
      id: '/seo-local/$ciudad'
      path: '/$ciudad'
      fullPath: '/seo-local/$ciudad'
      preLoaderRoute: typeof SeoLocalCiudadRouteImport
      parentRoute: typeof SeoLocalRoute
    }
    '/portfolio/$proyecto': {
      id: '/portfolio/$proyecto'
      path: '/$proyecto'
      fullPath: '/portfolio/$proyecto'
      preLoaderRoute: typeof PortfolioProyectoRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/diseno-web/$ciudad': {
      id: '/diseno-web/$ciudad'
      path: '/diseno-web/$ciudad'
      fullPath: '/diseno-web/$ciudad'
      preLoaderRoute: typeof DisenoWebCiudadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/cuanto-cuesta-pagina-web-restaurante': {
      id: '/blog/cuanto-cuesta-pagina-web-restaurante'
      path: '/cuanto-cuesta-pagina-web-restaurante'
      fullPath: '/blog/cuanto-cuesta-pagina-web-restaurante'
      preLoaderRoute: typeof BlogCuantoCuestaPaginaWebRestauranteRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/cuanto-cuesta-pagina-web-espana': {
      id: '/blog/cuanto-cuesta-pagina-web-espana'
      path: '/cuanto-cuesta-pagina-web-espana'
      fullPath: '/blog/cuanto-cuesta-pagina-web-espana'
      preLoaderRoute: typeof BlogCuantoCuestaPaginaWebEspanaRouteImport
      parentRoute: typeof BlogRoute
    }
    '/$landingType/$ciudad': {
      id: '/$landingType/$ciudad'
      path: '/$landingType/$ciudad'
      fullPath: '/$landingType/$ciudad'
      preLoaderRoute: typeof LandingTypeCiudadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogCuantoCuestaPaginaWebEspanaRoute: typeof BlogCuantoCuestaPaginaWebEspanaRoute
  BlogCuantoCuestaPaginaWebRestauranteRoute: typeof BlogCuantoCuestaPaginaWebRestauranteRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogCuantoCuestaPaginaWebEspanaRoute: BlogCuantoCuestaPaginaWebEspanaRoute,
  BlogCuantoCuestaPaginaWebRestauranteRoute:
    BlogCuantoCuestaPaginaWebRestauranteRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface PortfolioRouteChildren {
  PortfolioProyectoRoute: typeof PortfolioProyectoRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioProyectoRoute: PortfolioProyectoRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface SeoLocalRouteChildren {
  SeoLocalCiudadRoute: typeof SeoLocalCiudadRoute
}

const SeoLocalRouteChildren: SeoLocalRouteChildren = {
  SeoLocalCiudadRoute: SeoLocalCiudadRoute,
}

const SeoLocalRouteWithChildren = SeoLocalRoute._addFileChildren(
  SeoLocalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  BlogRoute: BlogRouteWithChildren,
  DisenoTiendaOnlineRoute: DisenoTiendaOnlineRoute,
  DisenoWebParaEmpresasRoute: DisenoWebParaEmpresasRoute,
  DisenoWebSeoRoute: DisenoWebSeoRoute,
  GoogleBusinessProfileRoute: GoogleBusinessProfileRoute,
  LandingPageRoute: LandingPageRoute,
  MantenimientoWebRoute: MantenimientoWebRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  SeoLocalRoute: SeoLocalRouteWithChildren,
  WebConReservasRoute: WebConReservasRoute,
  WebParaSectorRoute: WebParaSectorRoute,
  LandingTypeCiudadRoute: LandingTypeCiudadRoute,
  DisenoWebCiudadRoute: DisenoWebCiudadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
